### ISSUE TITLE
Error when using offset

### ISSUE THREAD

**Issue by jilleb** [NetherlandsForensicInstitute/tffsmount#1]
First of all: lovely tool, thank you!

When using an offset parameter, I get the following error:

```
2023-10-16 12:11:13,948 — tffsmount — INFO — Mounting image opt_ivi_C3.img.swup on mount point tmp
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/jille/tffsmount/tffsmount/__main__.py", line 35, in <module>
    main(args)
  File "/home/jille/tffsmount/tffsmount/__main__.py", line 14, in main
    mount(args.image, args.mount_point, args.offset)
  File "/home/jille/tffsmount/tffsmount/mount.py", line 65, in mount
    with Stream(image, offset) as stream:
  File "/home/jille/tffsmount/tffsmount/stream.py", line 12, in __enter__
    self.mm = mmap.mmap(
              ^^^^^^^^^^
OSError: [Errno 22] Invalid argument
```

The image I'm trying to mount has the following header:
![image](https://github.com/NetherlandsForensicInstitute/tffsmount/assets/8352494/6ebeaeed-1561-460b-878f-81e824473356)

When manually trimming the first 128 bytes, tffsmount can mount it without any issues (without the need for any offset imput), so I might be doing something wrong or there's a small bug in the code.

**Comment by JonathanHerrewijnen** [comment]
I think this might have to do with the kernel enforcing mmap() to use aligned offsets. (0x1000, 4096)?
